# name: Publish

# on:
#   push:
#     branches:
#       - production

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - uses: actions/setup-node@v1
#         with:
#           node-version: 12
#           registry-url: https://registry.npmjs.org/
#       - name: install
#         run: npm install
#       - name: build-prod
#         run: npm run build-prod
#       - name: publish
#       - run: npm publish --access public
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}